#####################################################################
# srsUE #2 — LTE mode, TELUS 4G digital twin, 3-UE demo pair
#
#   UE2 UL REP  tcp://*:2013       <- enb2 UL REQ
#   UE2 DL REQ  -> tcp://10.53.2.13:2012  (enb2 DL REP)
#
# PLMN: 302/221 (TELUS Mobility Canada)
# IMSI: 302221000000002  (generated via realizer/gen_user_db.py, seed=7)
#####################################################################

[rf]
freq_offset     = 0
tx_gain         = 0
rx_gain         = 0
nof_antennas    = 1
continuous_tx   = yes
device_name     = zmq
device_args     = tx_port=tcp://*:2013,rx_port=tcp://10.53.2.13:2012,base_srate=11.52e6

[rat.eutra]
dl_earfcn   = 3350
nof_carriers = 1

[rat.nr]
nof_carriers = 0

[pcap]
enable          = none
mac_filename    = /tmp/ue4g_mac.pcap
nas_filename    = /tmp/ue4g_nas.pcap

[log]
all_level       = info
phy_lib_level   = none
rrc_level       = debug
nas_level       = debug
all_hex_limit   = 128
filename        = /tmp/ue4g.log
file_max_size   = -1

[usim]
mode = soft
algo = milenage
opc  = 7C2999FDAFE593253CD654AF4DFAD714
k    = 3460BE31201E69FEDAA0EEE8B9997F5C
imsi = 302221000000002
imei = 353490069873320

[rrc]
release     = 9
ue_category = 4

[nas]
apn = internet

[gw]
netns      =
ip_devname = tun_srsue4g
ip_netmask = 255.255.255.0

[gui]
enable = false
